// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1654817031);
user_pref("browser.search.region", "US");
user_pref("browser.theme.dark-toolbar-theme", true);
user_pref("calendar.timezone.local", "America/New_York");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220521105013");
user_pref("extensions.lastAppVersion", "91.9.1");
user_pref("extensions.lastPlatformVersion", "91.9.1");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"9e336c40-c875-445d-a138-8e746f8313e2\",\"google@search.mozilla.org\":\"e0a8985a-4f9d-4b9d-a770-085c3ba17fd5\",\"ddg@search.mozilla.org\":\"21a0446b-05fd-40c2-8113-36b1bf2db554\",\"amazondotcom@search.mozilla.org\":\"080b14ba-8d49-488b-aecd-bfeec1a3c97d\",\"wikipedia@search.mozilla.org\":\"88f22d78-e40f-4e8a-829f-3d4708f944fa\",\"bing@search.mozilla.org\":\"01426bec-3234-4b55-8cfb-af1aea929926\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 32);
user_pref("mailnews.database.global.datastore.id", "5fc0652c-1d76-4c62-b5df-6c5ac24a584");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.9.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20220521105013");
